# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\외출일지\delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("background:rgb(252, 252, 252);")
        self.search_title_2 = QtWidgets.QLabel(Form)
        self.search_title_2.setGeometry(QtCore.QRect(140, 180, 251, 51))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(16)
        self.search_title_2.setFont(font)
        self.search_title_2.setObjectName("search_title_2")
        self.delete_name = QtWidgets.QPlainTextEdit(Form)
        self.delete_name.setGeometry(QtCore.QRect(390, 250, 211, 50))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.delete_name.setFont(font)
        self.delete_name.setObjectName("delete_name")
        self.delete_title = QtWidgets.QLabel(Form)
        self.delete_title.setGeometry(QtCore.QRect(280, 100, 231, 41))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(18)
        self.delete_title.setFont(font)
        self.delete_title.setObjectName("delete_title")
        self.search_title_3 = QtWidgets.QLabel(Form)
        self.search_title_3.setGeometry(QtCore.QRect(220, 250, 171, 51))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(16)
        self.search_title_3.setFont(font)
        self.search_title_3.setObjectName("search_title_3")
        self.btn_delete_student = QtWidgets.QPushButton(Form)
        self.btn_delete_student.setGeometry(QtCore.QRect(290, 360, 191, 71))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_delete_student.setFont(font)
        self.btn_delete_student.setStyleSheet("background:rgb(255, 150, 150);")
        self.btn_delete_student.setObjectName("btn_delete_student")
        self.delete_room_number = QtWidgets.QPlainTextEdit(Form)
        self.delete_room_number.setGeometry(QtCore.QRect(390, 180, 211, 50))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.delete_room_number.setFont(font)
        self.delete_room_number.setObjectName("delete_room_number")
        self.btn_back = QtWidgets.QPushButton(Form)
        self.btn_back.setGeometry(QtCore.QRect(290, 450, 191, 71))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background:rgb(200, 200, 200);")
        self.btn_back.setObjectName("btn_back")

        self.retranslateUi(Form)
        self.btn_back.clicked.connect(Form.btn_delete_to_edit) # type: ignore
        self.btn_delete_student.clicked.connect(Form.getDeleteInput) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.search_title_2.setText(_translate("Form", "호실 번호 입력:"))
        self.delete_title.setText(_translate("Form", "기숙사생 삭제"))
        self.search_title_3.setText(_translate("Form", "이름 입력:"))
        self.btn_delete_student.setText(_translate("Form", "삭제"))
        self.btn_back.setText(_translate("Form", "뒤로가기"))
