# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\외출일지\edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("background:rgb(252, 252, 252);")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(240, 190, 301, 71))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("background:rgb(255, 150, 150);")
        self.btn_add.setObjectName("btn_add")
        self.btn_minus = QtWidgets.QPushButton(Form)
        self.btn_minus.setGeometry(QtCore.QRect(240, 290, 301, 71))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("background:rgb(255, 180, 150);")
        self.btn_minus.setObjectName("btn_minus")
        self.title_2 = QtWidgets.QLabel(Form)
        self.title_2.setGeometry(QtCore.QRect(310, 100, 181, 61))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(18)
        self.title_2.setFont(font)
        self.title_2.setObjectName("title_2")
        self.btn_back = QtWidgets.QPushButton(Form)
        self.btn_back.setGeometry(QtCore.QRect(240, 390, 301, 71))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background:rgb(255, 255, 140);")
        self.btn_back.setObjectName("btn_back")

        self.retranslateUi(Form)
        self.btn_add.clicked.connect(Form.btn_edit_to_add) # type: ignore
        self.btn_minus.clicked.connect(Form.btn_edit_to_delete) # type: ignore
        self.btn_back.clicked.connect(Form.btn_edit_to_main) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_add.setText(_translate("Form", "기숙사생 추가"))
        self.btn_minus.setText(_translate("Form", "기숙사생 삭제"))
        self.title_2.setText(_translate("Form", "메뉴 선택"))
        self.btn_back.setText(_translate("Form", "뒤로가기"))
