# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\프로젝트\list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.student_list = QtWidgets.QListView(Form)
        self.student_list.setGeometry(QtCore.QRect(80, 89, 631, 441))
        self.student_list.setObjectName("student_list")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(260, 30, 381, 51))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "기숙사생 명단"))
