# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\외출일지\list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_list(object):
    def setupUi(self, list):
        list.setObjectName("list")
        list.resize(800, 600)
        list.setStyleSheet("background:rgb(252, 252, 252);")
        self.label = QtWidgets.QLabel(list)
        self.label.setGeometry(QtCore.QRect(280, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(list)
        self.scrollArea.setGeometry(QtCore.QRect(70, 138, 651, 381))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 649, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.student_list = QtWidgets.QLabel(list)
        self.student_list.setGeometry(QtCore.QRect(130, 530, 531, 51))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(12)
        self.student_list.setFont(font)
        self.student_list.setText("")
        self.student_list.setObjectName("student_list")
        self.label_2 = QtWidgets.QLabel(list)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 701, 51))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(list)
        QtCore.QMetaObject.connectSlotsByName(list)

    def retranslateUi(self, list):
        _translate = QtCore.QCoreApplication.translate
        list.setWindowTitle(_translate("list", "Form"))
        self.label.setText(_translate("list", "기숙사생 명단"))
        self.label_2.setText(_translate("list", "호실    이름          상태        업데이트 날짜"))
