# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\외출일지\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.btn_list = QtWidgets.QPushButton(MainWindow)
        self.btn_list.setGeometry(QtCore.QRect(300, 230, 380, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(220)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.btn_list.sizePolicy().hasHeightForWidth())
        self.btn_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_list.setFont(font)
        self.btn_list.setObjectName("btn_list")
        self.btn_status = QtWidgets.QPushButton(MainWindow)
        self.btn_status.setGeometry(QtCore.QRect(300, 330, 380, 81))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_status.setFont(font)
        self.btn_status.setObjectName("btn_status")
        self.btn_edit = QtWidgets.QPushButton(MainWindow)
        self.btn_edit.setGeometry(QtCore.QRect(300, 430, 380, 81))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_edit.setFont(font)
        self.btn_edit.setObjectName("btn_edit")
        self.btn_search = QtWidgets.QPushButton(MainWindow)
        self.btn_search.setGeometry(QtCore.QRect(300, 530, 380, 81))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(14)
        self.btn_search.setFont(font)
        self.btn_search.setObjectName("btn_search")
        self.title = QtWidgets.QLabel(MainWindow)
        self.title.setGeometry(QtCore.QRect(350, 110, 321, 111))
        font = QtGui.QFont()
        font.setFamily("궁서체")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setObjectName("title")

        self.retranslateUi(MainWindow)
        self.btn_list.clicked.connect(MainWindow.btn_main_to_list) # type: ignore
        self.btn_status.clicked.connect(MainWindow.btn_main_to_status) # type: ignore
        self.btn_edit.clicked.connect(MainWindow.btn_main_to_edit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.btn_list.setText(_translate("MainWindow", "기숙사생 명단 확인"))
        self.btn_status.setText(_translate("MainWindow", "특정 기숙사생 상태 확인"))
        self.btn_edit.setText(_translate("MainWindow", "기숙사생 추가 / 삭제"))
        self.btn_search.setText(_translate("MainWindow", "날짜 별 기숙사생 상태 확인"))
        self.title.setText(_translate("MainWindow", "외출일지"))
